@startuml
actor User

User -> BudgetParser : input(commandString)
activate BudgetParser

BudgetParser -> BudgetAttributes : new(input)
activate BudgetAttributes
BudgetAttributes --> BudgetParser : return BudgetAttributes
deactivate BudgetAttributes

BudgetParser -> BudgetCommand : create command (using attributes)
activate BudgetCommand
BudgetParser --> User : return BudgetCommand
deactivate BudgetParser

activate BudgetCommand

BudgetCommand -> BudgetList : execute()
activate BudgetList

BudgetList -> Budget : budget methods
activate Budget
Budget --> BudgetList : result / exception
deactivate Budget

BudgetList --> BudgetCommand : result / exception
deactivate BudgetList

BudgetCommand --> User : output result or error
deactivate BudgetCommand

note right of BudgetCommand : catches BudgetException

@enduml
