@startuml
actor User
participant ":UI" as UI
participant ":IncomeCommandParser" as Parser
participant ":IncomeParserResult" as Result
participant ":EditIncomeCommand" as EditCommand
participant ":IncomeManager" as Manager
participant ":Storage" as Storage
hide footbox

User -> UI : enters "edit 1 Bonus 500 Job 2025-04-01"
activate UI

UI -> Parser : parseEdit(input)
activate Parser

Parser -> Result : new IncomeParserResult(EditIncomeCommand, null)
activate Result

Result --> Parser
deactivate Result

Parser --> UI : IncomeParserResult instance
deactivate Parser

UI -> Result : getCommand()
activate Result

Result --> UI : EditIncomeCommand instance
deactivate Result

UI -> EditCommand : execute(Manager)
activate EditCommand

EditCommand -> Manager : editIncome(1, "Bonus", 500, 2025-04-01, "Job")
activate Manager

Manager -> Storage : saveFile(incomes)
activate Storage

Storage --> Manager
deactivate Storage

Manager --> EditCommand
deactivate Manager

EditCommand --> UI
deactivate EditCommand

deactivate UI
@enduml
