@startuml
hide circle
skinparam classAttributeIconSize 0

class utils.money.Money implements Comparable<Money> {
    - currency : Currency
    - amount : BigDecimal
    + increment(amount : BigDecimal) : void
    + increment(percentage : double) : void
    + compareTo(money : Money) : int
}

@enduml